/* eslint-disable unicorn/no-await-expression-member */
'use client'

import type { NextPage } from 'next'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import React from 'react'

import styles from './page.module.css'

const WalletDisconnectButtonDynamic = dynamic(
  async () =>
    (await import('@solana/wallet-adapter-react-ui')).WalletDisconnectButton,
  { ssr: false }
)
const WalletMultiButtonDynamic = dynamic(
  async () =>
    (await import('@solana/wallet-adapter-react-ui')).WalletMultiButton,
  { ssr: false }
)

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Solana adapter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.walletButtons}>
          <WalletMultiButtonDynamic />
          <WalletDisconnectButtonDynamic />
        </div>
      </main>
    </div>
  )
}

export default Home
